const emailsData = [
  {
    id: '0ze4j',
    subject: 'Dont join Tesla, join me!!',
    body: 'Im the better Elon, you should totaly join me',
    isRead: false,
    sentAt: 1671233940594,
    to: { fullName: 'Mahatma Appsus', email: 'user@appsus.com' },
    from: { fullName: 'Elon Barzani', email: 'elon5000@gmail.com' },
    status: 'inbox',
    isStar: false,
    file: '',
  },
  {
    id: 'OXeMG',
    subject: 'Join Tesla!',
    body: 'Join Best company, Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur animi necessitatibus explicabo id non ut.',
    isRead: true,
    sentAt: 1641233940594,
    to: { fullName: 'Mahatma Appsus', email: 'user@appsus.com' },
    from: { fullName: 'Elon Mask', email: 'tesle@tesla.com' },
    status: 'inbox',
    isStar: false,
    file: 'assets/pages/email/file-storage/imgs/image1.jpg',
  },
  {
    id: 'kSnfI',
    subject: 'Amazon Prime',
    body: 'You got a delivery, Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur animi necessitatibus explicabo id non ut.',
    isRead: false,
    sentAt: 1551143930594,
    to: { fullName: 'Mahatma Appsus', email: 'user@appsus.com' },
    from: { fullName: 'Amazon', email: 'amazon@walla.co.il' },
    status: 'inbox',
    isStar: false,
    file: '',
  },
  {
    id: 'lSpf2',
    subject: 'Old version returns',
    body: 'f@$% dat we going back to pirates.',
    isRead: true,
    sentAt: 1551132930594,
    to: { fullName: 'Mahatma Appsus', email: 'user@appsus.com' },
    from: { fullName: 'Maplestory', email: 'maple@nixon.com' },
    status: 'inbox',
    isStar: false,
    file: 'assets/pages/email/file-storage/imgs/image2.jpg',
  },
  {
    id: 'JYOJa2',
    subject: 'Hi',
    body: 'Would love to catch up sometimes',
    isRead: false,
    sentAt: 1551133930594,
    to: { fullName: 'Momo Mo', email: 'momo@momo.com' },
    from: { fullName: 'Mahatma Appsus', email: 'user@appsus.com' },
    status: 'sent',
    isStar: false,
    file: '',
  },
  {
    id: 'f4iuV',
    subject: 'Hi',
    body: 'Would love to catch up sometimes',
    isRead: false,
    sentAt: 1551133930594,
    to: { fullName: 'Momo Mo', email: 'momo@momo.com' },
    from: { fullName: 'Mahatma Appsus', email: 'user@appsus.com' },
    status: 'sent',
    isStar: false,
    file: 'assets/pages/email/file-storage/imgs/image3.jpg',
  },
  {
    id: '1y0Oq',
    subject: 'Hi',
    body: 'Would love to catch up sometimes',
    isRead: false,
    sentAt: 1551133930594,
    to: { fullName: 'Momo Mo', email: 'momo@momo.com' },
    from: { fullName: 'Mahatma Appsus', email: 'user@appsus.com' },
    status: 'draft',
    isStar: false,
    file: 'assets/pages/email/file-storage/imgs/image2.jpg',
  },
  {
    id: 'U2rfZ',
    subject: 'Hi',
    body: 'Would love to catch up sometimes',
    isRead: false,
    sentAt: 1551133930594,
    to: { fullName: 'Momo Mo', email: 'momo@momo.com' },
    from: { fullName: 'Mahatma Appsus', email: 'user@appsus.com' },
    status: 'draft',
    isStar: false,
    file: '',
  },
]

export default emailsData
