const emailsData = [
  {
    id: 'OXeMG',
    subject: 'Miss you!',
    body: 'Would love to catch up sometimes',
    isRead: false,
    sentAt: 1551133930594,
    to: 'momo@momo.com',
    category: 'inbox',
    isStar: false,
    file: '../../../assets/pages/email/file-storage/imgs/img1.jpg',
  },
  {
    id: 'JYOJa2',
    subject: 'Hi',
    body: 'Would love to catch up sometimes',
    isRead: false,
    sentAt: 1551133930594,
    to: 'momo@momo.com',
    category: 'sent',
    isStar: false,
    file: '',
  },
  {
    id: '1y0Oq',
    subject: 'Hi',
    body: 'Would love to catch up sometimes',
    isRead: false,
    sentAt: 1551133930594,
    to: 'momo@momo.com',
    category: 'draft',
    isStar: false,
    file: '',
  },
  {
    id: 'kSnfI',
    subject: 'Miss you!',
    body: 'Would love to catch up sometimes',
    isRead: false,
    sentAt: 1551133930594,
    to: 'momo@momo.com',
    category: 'inbox',
    isStar: false,
    file: '',
  },
  {
    id: 'f4iuV',
    subject: 'Hi',
    body: 'Would love to catch up sometimes',
    isRead: false,
    sentAt: 1551133930594,
    to: 'momo@momo.com',
    category: 'sent',
    isStar: false,
    file: '',
  },
  {
    id: 'U2rfZ',
    subject: 'Hi',
    body: 'Would love to catch up sometimes',
    isRead: false,
    sentAt: 1551133930594,
    to: 'momo@momo.com',
    category: 'draft',
    isStar: false,
    file: '',
  },
]

export default emailsData
